### ISSUE TITLE
In ubuntu 18.04 compile，when "file to patch:", what to input

### ISSUE THREAD

**Issue by xuws75** [OpenVisualCloud/Immersive-Video-Sample#19]
thanks

**Comment by U1X6WK** [comment]
Which command did you get when you executed this command?
Can you describe your problem in more detail?

**Comment by xuws75** [comment]
In compiling process, the last output message is：
+ wget -q https://curl.haxx.se/download/curl-7.66.0.tar.xz
+ tar xf curl-7.66.0.tar.xz
tar: curl-7.66.0.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
+ cd curl-7.66.0
./prebuild.sh: line 94: cd: curl-7.66.0: No such file or directory
+ cd /usr/local/include/libxml2
+ sudo mv libxml ../
mv: cannot move 'libxml' to '../libxml': Directory not empty
+ cd /mnt/e/code_study/open_visual_cloud/trunk/Immersive-Video-Sample/Immersive-Video-Sample/src/external/../build/external
+ download_dependencies server
+ cd /mnt/e/code_study/open_visual_cloud/trunk/Immersive-Video-Sample/Immersive-Video-Sample/src/external
+ '[' server == server ']'
+ ./build_glog.sh
./build_glog.sh: line 2: $'\r': command not found
+ ./build_Nokia_omaf.sh
./build_Nokia_omaf.sh: 31: ./build_Nokia_omaf.sh: Syntax error: end of file unexpected (expecting "then")
+ ./install_openHEVC.sh
./install_openHEVC.sh: 2: cd: can't cd to ../build/external
+ ./install_SVT.sh
./install_SVT.sh: 2: cd: can't cd to ../build/external
+ ./install_thrift.sh
./prebuild.sh: line 107: ./install_thrift.sh: No such file or directory
+ ./install_FFmpeg.sh server
+ TARGET=server
+ ORIGIN_PATH=/mnt/e/code_study/open_visual_cloud/trunk/Immersive-Video-Sample/Immersive-Video-Sample/src/external
+ cd ..
+ '[' '!' -d ./FFmpeg ']'
+ cd FFmpeg
+ '[' server == server ']'
+ git checkout release/4.1
error: pathspec 'release/4.1' did not match any file(s) known to git.
+ git checkout c2ac3b8e6a040e33d53fa13548848c8ba981a8e4
fatal: reference is not a tree: c2ac3b8e6a040e33d53fa13548848c8ba981a8e4
+ cd -
/mnt/e/code_study/open_visual_cloud/trunk/Immersive-Video-Sample/Immersive-Video-Sample/src
+ patch -p1
(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/FFmpeg/Changelog b/FFmpeg/Changelog
|index 0343ce9..f1c70df 100644
|--- a/FFmpeg/Changelog
|+++ b/FFmpeg/Changelog
--------------------------
File to patch:

**Comment by xuws75** [comment]
The command is：./build.sh server y

**Comment by U1X6WK** [comment]
Hi xuws75,

I reproduced your issue by following commands:

```bash
cd Immersive-Video-Sample/src
mkdir FFmpeg
patch -p1 < ffmpeg/patches/FFmpeg_OMAF.patch
```

Seems FFmpeg wasn't download successfully and the file "Changelog" doesn't exist. Could you checkout if there's a file named "Changelog" located at Immersive-Video-Sample/src/FFmpeg?

**Comment by xuws75** [comment]
After I copied ffmpeg4.2.2 source code to /src/ffmpeg, run “patch -p1 < ffmpeg/patches/FFmpeg_OMAF.patch”， There are still compilation errors.
Operating system:Ubuntu 18.04 in win10.

CC      libavcodec/cpia.o
src/libavcodec/codec_desc.c:131:22: error: ‘AV_CODEC_ID_HEVCBYPASSVIDEO’ undeclared here (not in a function); did you mean ‘AV_CODEC_ID_CLEARVIDEO’?
         .id        = AV_CODEC_ID_HEVCBYPASSVIDEO,
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                      AV_CODEC_ID_CLEARVIDEO
src/libavcodec/codec_desc.c:138:22: error: ‘AV_CODEC_ID_H264BYPASSVIDEO’ undeclared here (not in a function); did you mean ‘AV_CODEC_ID_HEVCBYPASSVIDEO’?
         .id        = AV_CODEC_ID_H264BYPASSVIDEO,
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                      AV_CODEC_ID_HEVCBYPASSVIDEO
src/libavcodec/codec_desc.c: In function ‘avcodec_descriptor_next’:
src/libavcodec/codec_desc.c:3351:34: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
     if (prev - codec_descriptors < FF_ARRAY_ELEMS(codec_descriptors) - 1)
                                  ^
src/ffbuild/common.mak:59: recipe for target 'libavcodec/codec_desc.o' failed
make: *** [libavcodec/codec_desc.o] Error 1
make: *** Waiting for unfinished jobs....
+ sudo make install
AR      libavdevice/libavdevice.a
INSTALL libavdevice/libavdevice.a
GEN     libavdevice/libavdevice.ver
GEN     libavfilter/libavfilter.ver
GEN     libswscale/libswscale.ver
GEN     libavutil/libavutil.ver
LD      libavutil/libavutil.so.56
LD      libswscale/libswscale.so.5
GEN     libpostproc/libpostproc.ver
LD      libpostproc/libpostproc.so.55
GEN     libavformat/libavformat.ver
CC      libavcodec/codec_desc.o
src/libavcodec/codec_desc.c:131:22: error: ‘AV_CODEC_ID_HEVCBYPASSVIDEO’ undeclared here (not in a function); did you mean ‘AV_CODEC_ID_CLEARVIDEO’?
         .id        = AV_CODEC_ID_HEVCBYPASSVIDEO,
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                      AV_CODEC_ID_CLEARVIDEO
src/libavcodec/codec_desc.c:138:22: error: ‘AV_CODEC_ID_H264BYPASSVIDEO’ undeclared here (not in a function); did you mean ‘AV_CODEC_ID_HEVCBYPASSVIDEO’?
         .id        = AV_CODEC_ID_H264BYPASSVIDEO,
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                      AV_CODEC_ID_HEVCBYPASSVIDEO
src/libavcodec/codec_desc.c: In function ‘avcodec_descriptor_next’:
src/libavcodec/codec_desc.c:3351:34: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
     if (prev - codec_descriptors < FF_ARRAY_ELEMS(codec_descriptors) - 1)
                                  ^
src/ffbuild/common.mak:59: recipe for target 'libavcodec/codec_desc.o' failed
make: *** [libavcodec/codec_desc.o] Error 1

2020-03-06 

xuws 



发件人：Kang Xin <notifications@github.com>
发送时间：2020-03-06 10:15
主题：Re: [OpenVisualCloud/Immersive-Video-Sample] In ubuntu 18.04 compile，when "file to patch:", what to input (#19)
收件人："OpenVisualCloud/Immersive-Video-Sample"<Immersive-Video-Sample@noreply.github.com>
抄送："xuws75"<xuws@cybercloud.com.cn>,"Author"<author@noreply.github.com>

Hi xuws75,
I reproduced your issue by following commands:
cd Immersive-Video-Sample/src
mkdir FFmpeg
patch -p1 < ffmpeg/patches/FFmpeg_OMAF.patch
Seems FFmpeg wasn't download successfully and the file "Changelog" doesn't exist. Could you checkout if there's a file named "Changelog" located at Immersive-Video-Sample/src/FFmpeg?

**Comment by U1X6WK** [comment]
@xuws75 

Refer to lines in "Immersive-Video-Sample/src/external/install_FFmpeg.sh" as following, please make sure the branch of your FFmpeg code is correct before patch step.

```bash
cd FFmpeg
if [ ${TARGET} == "server" ] ; then
    git checkout release/4.1
    git checkout c2ac3b8e6a040e33d53fa13548848c8ba981a8e4
    cd -
    patch -p1 < ffmpeg/patches/FFmpeg_OMAF.patch
    # Omit other steps
fi
```

**Comment by xuws75** [comment]
+ TARGET=server
+ ORIGIN_PATH=/mnt/e/code_study/open_visual_cloud/trunk/Immersive-Video-Sample/Immersive-Video-Sample/src/external
+ cd ..
+ '[' '!' -d ./FFmpeg ']'
+ cd FFmpeg
+ '[' server == server ']'
+ git checkout release/4.1
error: pathspec 'release/4.1' did not match any file(s) known to git.
+ git checkout c2ac3b8e6a040e33d53fa13548848c8ba981a8e4
fatal: reference is not a tree: c2ac3b8e6a040e33d53fa13548848c8ba981a8e4

2020-03-06 

xuws 



发件人：Kang Xin <notifications@github.com>
发送时间：2020-03-06 14:03
主题：Re: [OpenVisualCloud/Immersive-Video-Sample] In ubuntu 18.04 compile，when "file to patch:", what to input (#19)
收件人："OpenVisualCloud/Immersive-Video-Sample"<Immersive-Video-Sample@noreply.github.com>
抄送："xuws75"<xuws@cybercloud.com.cn>,"Mention"<mention@noreply.github.com>

@xuws75
Refer to lines in "Immersive-Video-Sample/src/external/install_FFmpeg.sh" as following, please make sure the branch of your FFmpeg code is correct before patch step.
cd FFmpeg
if [ ${TARGET} == "server" ] ; then
    git checkout release/4.1
    git checkout c2ac3b8e6a040e33d53fa13548848c8ba981a8e4
    cd -
    patch -p1 < ffmpeg/patches/FFmpeg_OMAF.patch
    # Omit other steps
fi

**Comment by U1X6WK** [comment]
@xuws75 

Try `git fetch --all` before `git checkout release/4.1` to get remote branch.

Or run `git clone https://github.com/FFmpeg/FFmpeg.git` to get a updated repo.

**Comment by xuws75** [comment]
I copy ffmepg4.1.5 sourcecode to src/ffmpeg,compiling messsage is：

CC      libavcodec/sbcenc.o
CC      libavcodec/sbrdsp.o
CC      libavcodec/sbrdsp_fixed.o
make: *** No rule to make target 'src/libavcodec/scpr3.c', needed by 'libavcodec/scpr.o'.  Stop.
make: *** Waiting for unfinished jobs....
+ sudo make install
AR      libavdevice/libavdevice.a
INSTALL libavdevice/libavdevice.a
GEN     libavdevice/libavdevice.ver
GEN     libavfilter/libavfilter.ver
GEN     libswscale/libswscale.ver
GEN     libavutil/libavutil.ver
LD      libavutil/libavutil.so.56
LD      libswscale/libswscale.so.5
GEN     libpostproc/libpostproc.ver
LD      libpostproc/libpostproc.so.55
GEN     libavformat/libavformat.ver
make: *** No rule to make target 'src/libavcodec/scpr3.c', needed by 'libavcodec/scpr.o'.  Stop.
2020-03-06 

xuws 



发件人：Kang Xin <notifications@github.com>
发送时间：2020-03-06 14:50
主题：Re: [OpenVisualCloud/Immersive-Video-Sample] In ubuntu 18.04 compile，when "file to patch:", what to input (#19)
收件人："OpenVisualCloud/Immersive-Video-Sample"<Immersive-Video-Sample@noreply.github.com>
抄送："xuws75"<xuws@cybercloud.com.cn>,"Mention"<mention@noreply.github.com>

@xuws75
Try git fetch --all before git checkout release/4.1 to get remote branch.
Or run git clone https://github.com/FFmpeg/FFmpeg.git to get a updated repo.

**Comment by U1X6WK** [comment]
> In compiling process, the last output message is：
> 
> * wget -q https://curl.haxx.se/download/curl-7.66.0.tar.xz
> * tar xf curl-7.66.0.tar.xz
>   tar: curl-7.66.0.tar.xz: Cannot open: No such file or directory
>   tar: Error is not recoverable: exiting now

According to your comment before, your download of curl package is not success.
Can you check your Internet connection please? Seems all of dependencies including FFmpeg and curl are not successfully downloaded.

**Comment by xuws75** [comment]
libDistributedEncoder.so and libEncoder.so in \Immersive-Video-Sample\Immersive-Video-Sample-master\Immersive-Video-Sample-master\src\ffmpeg\dependency, what are they compiled from?
where the interface in DistributedEncoderAPI.h are invoked?


2020-03-09 E:\code_study\open_visual_cloud\trunk\Immersive-Video-Sample\Immersive-Video-Sample-master\Immersive-Video-Sample-master\src\ffmpeg\dependency

xuws 



发件人：Kang Xin <notifications@github.com>
发送时间：2020-03-09 10:04
主题：Re: [OpenVisualCloud/Immersive-Video-Sample] In ubuntu 18.04 compile，when "file to patch:", what to input (#19)
收件人："OpenVisualCloud/Immersive-Video-Sample"<Immersive-Video-Sample@noreply.github.com>
抄送："xuws75"<xuws@cybercloud.com.cn>,"Mention"<mention@noreply.github.com>

In compiling process, the last output message is：
wget -q https://curl.haxx.se/download/curl-7.66.0.tar.xz 
tar xf curl-7.66.0.tar.xz
tar: curl-7.66.0.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now 
According to your comment before, your download of curl package is not success.
Can you check your Internet connection please? Seems all of dependencies including FFmpeg and curl are not successfully downloaded.

**Comment by U1X6WK** [comment]
@xuws75 
These libraries are built from our encoder pipeline codes, which you can refer to `src/doc/Immersive_Video_Delivery_Architecture.md` for more information.
Interfaces in DistributedEncoderAPI.h are invoked in FFmpeg, written in `src/ffmpeg/patches/FFmpeg_OMAF.patch`.

**Comment by xuws75** [comment]
ffmpeg -i [file] -input_type 1 -c:v:0 distributed_encoder -s:0 3840x1920 -tile_row:0 6 -tile_column:0 10 -config_file:0 config_high.txt -g:0 15 -b:0 30M -map 0:v -c:v:1 distributed_encoder -s:1 1024x640 -tile_row:1 2 -tile_column:1 4 -config_file:1 config_low.txt -g:1 15 -b:1 5M -map 0:v -f omaf_packing -is_live 0 -split_tile 1 -seg_duration 1 -window_size 20 -extra_window_size 30 -base_url http://[server ip]]/OMAFStatic_4k/ -out_name Test /usr/local/nginx/html/OMAFStatic_4k/

What is config_high.txt and config_low.txt? Can you give me a template?
2020-03-13 

xuws 



发件人：Kang Xin <notifications@github.com>
发送时间：2020-03-13 10:22
主题：Re: [OpenVisualCloud/Immersive-Video-Sample] In ubuntu 18.04 compile，when "file to patch:", what to input (#19)
收件人："OpenVisualCloud/Immersive-Video-Sample"<Immersive-Video-Sample@noreply.github.com>
抄送："xuws75"<xuws@cybercloud.com.cn>,"Mention"<mention@noreply.github.com>

@xuws75
These libraries are built from our encoder pipeline codes, which you can refer to src/doc/Immersive_Video_Delivery_Architecture.md for more information.
Interfaces in DistributedEncoderAPI.h are invoked in FFmpeg, written in src/ffmpeg/patches/FFmpeg_OMAF.patch.

**Comment by U1X6WK** [comment]
@xuws75 
You can get a template referring to `OMAF-Sample/server/run.sh`.

**Comment by xuws75** [comment]
[root@localhost test]# echo "ip 127.0.0.1 port 9089" > config_low.txt
[root@localhost test]# echo "ip 127.0.0.1 port 9090" > config_high.txt
[root@localhost test]# ./ffmpeg -i diving.mp4 -input_type 1 -c:v:0 distributed_encoder -s:0 3840x1920 -tile_row:0 6 -tile_column:0 10 -config_file:0 config_high.txt -g:0 15 -b:0 30M -map 0:v -c:v:1 distributed_encoder -s:1 1024x640 -tile_row:1 2 -tile_column:1 4 -config_file:1 config_low.txt -g:1 15 -b:1 5M -map 0:v -f omaf_packing -is_live 0 -split_tile 1 -seg_duration 1 -window_size 20 -extra_window_size 30 -base_url http://192.168.70.129/OMAFStatic_4k/ -out_name Test ./xyz/
ffmpeg version N-92246-gc2ac3b8 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.1 (GCC) 20170216 (Red Hat 6.3.1-3)
  configuration: --prefix=/usr --libdir=/usr/lib --enable-static --disable-shared --enable-gpl --enable-nonfree --disable-optimizations --disable-vaapi --enable-libDistributedEncoder --enable-libVROmafPacking --extra-cflags='"-I/root/work/immersive/Immersive-Video-Sample/src/VROmafPacking/"' --extra-cflags='"-I/root/work/immersive/Immersive-Video-Sample/src/360SCVP/"' --extra-ldflags='"-L/root/work/immersive/Immersive-Video-Sample/src/build/server/VROmafPacking/"' --extra-ldflags='"-L/root/work/immersive/Immersive-Video-Sample/src/build/server/360SCVP"'
  libavutil      56. 19.101 / 56. 19.101
  libavcodec     58. 33.102 / 58. 33.102
  libavformat    58. 19.102 / 58. 19.102
  libavdevice    58.  4.106 / 58.  4.106
  libavfilter     7. 37.100 /  7. 37.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'diving.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.25.101
  Duration: 00:01:09.29, start: 0.000000, bitrate: 15576 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 3840x1920 [SAR 1:1 DAR 2:1], 15455 kb/s, 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> hevc (distributed_encoder))
  Stream #0:0 -> #0:1 (h264 (native) -> hevc (distributed_encoder))
Press [q] to stop, [?] for help
sh: /root/WorkerServer: Permission denied
Thrift: Fri Mar 13 16:17:45 2020 TSocket::open() connect() <Host: 127.0.0.1 Port: 9090>: Connection refused
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0313 16:17:45.970857 12487 RemoteSolution_Thrift.cpp:95] ERROR: connect() failed: Connection refused
E0313 16:17:45.970970 12487 RemoteSolution_Thrift.cpp:336] ERROR: Called write on non-open socket
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

what error?


2020-03-13 

xuws 



发件人：Kang Xin <notifications@github.com>
发送时间：2020-03-13 15:19
主题：Re: [OpenVisualCloud/Immersive-Video-Sample] In ubuntu 18.04 compile，when "file to patch:", what to input (#19)
收件人："OpenVisualCloud/Immersive-Video-Sample"<Immersive-Video-Sample@noreply.github.com>
抄送："xuws75"<xuws@cybercloud.com.cn>,"Mention"<mention@noreply.github.com>

@xuws75
You can get a template referring to OMAF-Sample/server/run.sh.

**Comment by U1X6WK** [comment]
@xuws75 

> sh: /root/WorkerServer: Permission denied

You need root privileges to execute this command.

**Comment by xuws75** [comment]
./ffmpeg -i diving.mp4 -input_type 1 -c:v:0 distributed_encoder -s:0 3840x1920 -tile_row:0 6 -tile_column:0 10 -config_file:0 config_high.txt -g:0 15 -b:0 30M -map 0:v -c:v:1 distributed_encoder -s:1 1024x640 -tile_row:1 2 -tile_column:1 4 -config_file:1 config_low.txt -g:1 15 -b:1 5M -map 0:v -f omaf_packing -is_live 0 -split_tile 1 -seg_duration 1 -window_size 20 -extra_window_size 30 -base_url http://192.168.70.129/OMAFStatic_4k/ -out_name Test ./xyz/

run end, where are output video and audio?  What directory?

2020-03-14 

xuws 



发件人：Kang Xin <notifications@github.com>
发送时间：2020-03-13 16:37
主题：Re: [OpenVisualCloud/Immersive-Video-Sample] In ubuntu 18.04 compile，when "file to patch:", what to input (#19)
收件人："OpenVisualCloud/Immersive-Video-Sample"<Immersive-Video-Sample@noreply.github.com>
抄送："xuws75"<xuws@cybercloud.com.cn>,"Mention"<mention@noreply.github.com>

@xuws75
sh: /root/WorkerServer: Permission denied
You need root privileges to execute this command.

**Comment by xuws75** [comment]
./ffmpeg -i diving.mp4 -input_type 1 -c:v:0 distributed_encoder -s:0 3840x1920 -tile_row:0 6 -tile_column:0 10 -config_file:0 config_high.txt -g:0 15 -b:0 30M -map 0:v -c:v:1 distributed_encoder -s:1 1024x640 -tile_row:1 2 -tile_column:1 4 -config_file:1 config_low.txt -g:1 15 -b:1 5M -map 0:v -f omaf_packing -is_live 0 -split_tile 1 -seg_duration 1 -window_size 20 -extra_window_size 30 -base_url http://192.168.70.129/OMAFStatic_4k/ -out_name Test ./xyz/

run end, where are output video and audio?  What directory?
2020-03-16 

xuws 



发件人：Kang Xin <notifications@github.com>
发送时间：2020-03-13 16:37
主题：Re: [OpenVisualCloud/Immersive-Video-Sample] In ubuntu 18.04 compile，when "file to patch:", what to input (#19)
收件人："OpenVisualCloud/Immersive-Video-Sample"<Immersive-Video-Sample@noreply.github.com>
抄送："xuws75"<xuws@cybercloud.com.cn>,"Mention"<mention@noreply.github.com>

@xuws75
sh: /root/WorkerServer: Permission denied
You need root privileges to execute this command.
