### ISSUE TITLE
libDistributedEncoder.so

### ISSUE THREAD

**Issue by chenminnj** [OpenVisualCloud/Immersive-Video-Sample#42]
Hi，
I am  new to Immersive-Video-Sample. 
I notice there are two library in "src\ffmpeg\dependency" --libDistributedEncoder.so and libEncoder.so.
What is the use and are they open source?
Thanks.

**Comment by hzhan80** [comment]
The 2 libraries are used to encode tiled stream with some strategies. The code of 2 libary isn't open source yet.
