### ISSUE TITLE
Distribute Encoder Plugin

### ISSUE THREAD

**Issue by felixyangtw** [OpenVisualCloud/Immersive-Video-Sample#44]
Hi:
    We will plan to build the VR FOV system. I have some questions about Distribute Encoder Plugin. Please help, thanks.
1. Is it use svt-HEVC? The range of tile_column and tile_row are 1~256, however, the ranage of them are 1~16. What ranges are correct?
2. How should I set HDR information by Distribute Encoder Plugin. I found only one params hdr. However, many params(ex.MaxCLL..) should be set. SVT-HEVC offers these params for HDR too.
3. Could I use SVT-HEVC directly instead of via Distribute Encoder Plugin?
4. Will the source of Distribute Encoder Plugin release in the future?

**Comment by hzhan80** [comment]
Glad to know you will build it. 
1. The implementation is based on SVT-HEVC now. Each tile must comply with SVT requirements: 1. 64-align with width and height; 2. minimum size of tile: width =256, height =256
2. There are only limited parameters configurable from the plugin
3. Yes, you can use SVT-HEVC directly. but there is some requirement for encoded stream: https://github.com/OpenVisualCloud/Immersive-Video-Sample/blob/master/src/doc/Immersive_Video_Delivery_OMAF_Packing.md
4.  so far, there is no plan to release the source of the plugin yet.

**Comment by felixyangtw** [comment]
Thanks for your reply.
Regarding to 1, I read the document https://github.com/OpenVisualCloud/SVT-HEVC/blob/master/Docs/svt-hevc_encoder_user_guide.md, and find the range of TileRowCount and TileColumnCount are both 1~16. However, the range of tile_column and tile_row of Distribute Encoder Plugin are both 1~256. I am confused to them. I think they should be the same becuase Distribute Encoder Plugin is based on SVT-HEVC.

**Comment by U1X6WK** [comment]
Hi @felixyangtw , thanks for your kind check.

This is a document typo. As you mentioned, Distribute Encoder Plugin is based on SVT-HEVC. Restrictions on tile size are:

 - Greater or equal to 256.
 - Divisible by 64.

Any configuration illegal to SVT-HEVC will cause false error in init process.
