### ISSUE TITLE
Fail to link libDistributedEncoder.so

### ISSUE THREAD

**Issue by felixyangtw** [OpenVisualCloud/Immersive-Video-Sample#45]
Hi:
    I try to build ffmpeg for server. I use the followoing configure:
./configure --prefix=/home/felix/prog_work/intel_omaf/ --libdir=/home/felix/prog_work/intel_omaf/target/lib --enable-static --disable-shared --enable-gpl --enable-nonfree --disable-optimizations --disable-vaapi --enable-libDistributedEncoder \
--extra-cflags="-I/home/felix/prog_work/intel_omaf/target/include/DistributedEncoder -I/home/felix/prog_work/intel_omaf/package/Immersive-Video-Sample-master/src/360SCVP" \
--extra-ldflags="-L/home/felix/prog_work/intel_omaf/target/lib -lDistributedEncoder"

and then type:
make -j `nproc`

The following errors are generated:
LD	ffmpeg_g
/usr/bin/ld: libavcodec/libavcodec.a(distributed_encoder.o): in function `de_init':
/home/felix/prog_work/intel_omaf/src/FFmpeg/libavcodec/distributed_encoder.c:245: undefined reference to `DistributedEncoder_Init'
/usr/bin/ld: libavcodec/libavcodec.a(distributed_encoder.o): in function `de_send_frame':
/home/felix/prog_work/intel_omaf/src/FFmpeg/libavcodec/distributed_encoder.c:299: undefined reference to `DistributedEncoder_Process'
/usr/bin/ld: /home/felix/prog_work/intel_omaf/src/FFmpeg/libavcodec/distributed_encoder.c:340: undefined reference to `DistributedEncoder_Process'
/usr/bin/ld: libavcodec/libavcodec.a(distributed_encoder.o): in function `de_receive_packet':
/home/felix/prog_work/intel_omaf/src/FFmpeg/libavcodec/distributed_encoder.c:362: undefined reference to `DistributedEncoder_GetPacket'
/usr/bin/ld: /home/felix/prog_work/intel_omaf/src/FFmpeg/libavcodec/distributed_encoder.c:374: undefined reference to `DistributedEncoder_GetPacket'
/usr/bin/ld: /home/felix/prog_work/intel_omaf/src/FFmpeg/libavcodec/distributed_encoder.c:411: undefined reference to `DistributedEncoder_GetParam'
/usr/bin/ld: libavcodec/libavcodec.a(distributed_encoder.o): in function `de_close':
/home/felix/prog_work/intel_omaf/src/FFmpeg/libavcodec/distributed_encoder.c:491: undefined reference to `DistributedEncoder_Destroy'
collect2: error: ld returned 1 exit status
make: *** [Makefile:108：ffmpeg_g] 錯誤 1

Please help me. Thanks!

**Comment by U1X6WK** [comment]
Seems the head file of distributed encoder was not found, please try add `--extra-cflags="-I/path/to/Immersive-video-sample/src/ffmpeg/dependency/"`.

**Comment by U1X6WK** [comment]
According to our build process, after running `./build.sh server y` successfully(located at Immersive-video-sample/src/external), there will be a FFmpeg build at `Immersive-video-sample/src/build/server/ffmpeg`.

**Comment by felixyangtw** [comment]
Thanks for your help! I can compile it.
