### ISSUE TITLE
Fail to compile ffmpeg when --enable-libOmafDashAccess

### ISSUE THREAD

**Issue by felixyangtw** [OpenVisualCloud/Immersive-Video-Sample#46]
Hi:
     When I compile ffmpeg with --enable-libOmafDashAccess, it can't  build. The following are the error messages:
libavformat/tiled_dash_dec.c:163:15: error: ‘HeadSetInfo’ {aka ‘struct HEADSETINFO’} has no member named ‘input_geoType’
  163 |     clientInfo->input_geoType = E_SVIDEO_EQUIRECT;
      |               ^~
libavformat/tiled_dash_dec.c:164:15: error: ‘HeadSetInfo’ {aka ‘struct HEADSETINFO’} has no member named ‘output_geoType’
  164 |     clientInfo->output_geoType = E_SVIDEO_VIEWPORT;
      |               ^~

I checked data_type.h and found input_geoType and output_geoType are not defined in data_type.h. What should I do? Thanks!

**Comment by ChenXiaomin0306** [comment]
You can now delete these two lines code. And we have already updated these codes but this update will be open in later release.

**Comment by felixyangtw** [comment]
Thanks! I will try it!
