### ISSUE TITLE
License of video files

### ISSUE THREAD

**Issue by veikk0** [OpenVisualCloud/Immersive-Video-Sample#48]
I was wondering whether the video files themselves are under a free license. The [License](https://github.com/OpenVisualCloud/Immersive-Video-Sample#license) section of the readme mentions OMAF sample and WebRTC sample code, but not the video files in the Sample-Videos directory.

High-quality immersive video files are already difficult to find, and if these ones were freely licensed, they could be used as test material by various open-source projects.

**Comment by hzhan80** [comment]
The video file is under the same license of the project. and you can get sample clips from camera official site such as Insta360.
