### ISSUE TITLE
OMAF-Sample server gets size=N/A and bitrate=N/A

### ISSUE THREAD

**Issue by kuroneko306** [OpenVisualCloud/Immersive-Video-Sample#75]
I have successfully built OMAF-Sample server on CentOS 7.

However, when I tried to run the server, it always show "size=N/A" and "bitrate=N/A".
It always show something like the line below:
`frame=   15 fps= 11 q=-0.0 q=-0.0 size=N/A time=00:00:00.13 bitrate=N/A speed=0.0993x`

If I run the client when the server is running, the client will show that it is timed out without receiving any data.

Also I got a warning each time when I try to run the server. The warning says:
`SVT [WARNING] Elevated privileges required to run with real-time policies! Check Linux Best Known Configuration in User Guide to run application in real-time without elevated privileges!`
It is not clear if this warning is related to the N/A problem.

Any help on telling what may cause the problem will be appreciated.

**Comment by U1X6WK** [comment]
If you are using LIVE mode, this may be a performance issue since the log shows fps of server is too low.

[Our test environment](https://github.com/OpenVisualCloud/Immersive-Video-Sample/tree/master/OMAF-Sample#test-environment-hardware) to be a comparance here.

Also, `"size=N/A" and "bitrate=N/A"` this line doesn't need to bother since this is a FFmpeg log, and the pipeline using plugins to process these indicators instead of FFmpeg itself.

**Comment by kuroneko306** [comment]
Thanks for the reply.
It seems that my server CPU is much weaker than that of the test environment. I will try to build and run the program with another server.

May I ask another question.
I found that there is an error message popped up during the building process.
`gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc -I/usr/include/python2.7 -c src/ext/module.cpp -o build/temp.linux-x86_64-2.7/src/ext/module.o
[91msrc/ext/module.cpp:20:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
[0m()
********************************************************************************
An error occurred while trying to compile with the C extension enabled
Attempting to build without the extension now
********************************************************************************`

It seems that gcc is unable to find "Python.h" even if I have installed the Python2.7 packages at "/usr/include/python2.7".
Is it an issue to be bother with? Or the program can still work without the C extension enabled?

**Comment by U1X6WK** [comment]
Please provide the command you ran into this error, this is also the first time I met.

>  Or the program can still work without the C extension enabled?

So have you tried as you said?
