### ISSUE TITLE
thrift ver.0.12.0 package has been removed from the current url

### ISSUE THREAD

**Issue by kuroneko306** [OpenVisualCloud/Immersive-Video-Sample#76]
This project requires "thrift 0.12.0" package from the url "http://apache.osuosl.org/thrift/0.12.0/"
However, after the 0.16.0 version released in Feb.2022, the package has been removed from the url above in 16Mar.2022.
The package has been moved to archive, with the url "http://archive.apache.org/dist/thrift/0.12.0/"

Shifting to thrift 0.16.0 causes some unknown issue (maybe related to FFMPEG module) in the OMAF server for my case.
So modify the url in L28 "/Immersive-Video-Sample-master/src/external/install_thrift.sh" to the new archived url may help.

**Comment by kuroneko306** [comment]
Also the url in 
L144 "/Immersive-Video-Sample-master/src/external/dockerfile"
L144 "/Immersive-Video-Sample-master/src/external/Dockerfile"
L149 "/Immersive-Video-Sample-master/OMAF-Sample/server/Dockerfile"
need to be modified to the new archived url.

Using thrift 0.12.0 makes the OMAF program works fine.
I am not able to figure out why thrift 0.16.0 doesn't work, however the archived 0.12.0 version still works fine, so 4 lines of modifying can easily bring the program back to work.

**Comment by kuroneko306** [comment]
The url "http://zlib.net/zlib-1.12.1.tar.gz" has been removed after the ver. 1.12.2 release in Mar27.2022.
Shifting to ver. 1.12.2 doesn't seem to cause any problem.
zlib ver. 1.12.2 can be obtained from the url "http://zlib.net/zlib-1.12.2.tar.gz".

**Comment by U1X6WK** [comment]
Thanks for your url updates @kuroneko306, links you mentioned will update in next release.

**Comment by EitanGoldfrad** [comment]
@kuroneko306 you mean version 1.2.12

**Comment by U1X6WK** [comment]
> Thanks for your url updates @kuroneko306, links you mentioned will update in next release.

Close this issue as mentioned.
