### ISSUE TITLE
ERROR: DistributedEncoder not found using pkg-config

### ISSUE THREAD

**Issue by EitanGoldfrad** [OpenVisualCloud/Immersive-Video-Sample#80]
Hi, I've been trying to compile the server component for the OMAF-sample but I get the following error:

`ERROR: DistributedEncoder not found using pkg-config`

I've tried building the docker image and compiling from source code, 
I've tried the latest git head as well as release 1.8.0 source code

My server is CentOS 7 and i've installed devtoolset-7 for the required compilers.

Any idea what the issue is?

**Comment by U1X6WK** [comment]
Can you provide the last error logs in `src/build/server/ffmpeg/ffbuild/config.log`?

**Comment by congnguyen** [comment]
Hi, @U1X6WK 
I have same issue. Here is the config.log I have. Please help us to clarify the problem. Thank you!
[config.log](https://github.com/OpenVisualCloud/Immersive-Video-Sample/files/8629193/config.log)

**Comment by U1X6WK** [comment]
> Hi, @U1X6WK I have same issue. Here is the config.log I have. Please help us to clarify the problem. Thank you! [config.log](https://github.com/OpenVisualCloud/Immersive-Video-Sample/files/8629193/config.log)

As the bottom of file you provided indicates:
```
/usr/bin/ld: cannot find -lthrift
/usr/bin/ld: cannot find -lthriftnb
```

thrift was not installed correctly, please refer to #76.

**Comment by congnguyen** [comment]
Thanks @U1X6WK . Issues is resolved

**Comment by congnguyen** [comment]
Hi @U1X6WK . I have a new issue when i run OMAF sample.
Below are the problem and config.xml I have set up
![image](https://user-images.githubusercontent.com/2325195/166889815-b32de739-628d-444a-a0aa-340520ba211c.png)
![image](https://user-images.githubusercontent.com/2325195/166890191-010c2b16-f93b-4f82-8c75-a15628449384.png)
Thank you !

**Comment by U1X6WK** [comment]
You need a running environment supports X11, as the log says.

I guess you are running client in a terminal and it doesn't support X11 display.

**Comment by congnguyen** [comment]
I am running on Ubuntu 18.04 as guide write and also installed some libs relative to x11 . But problem is not resolved

**Comment by EitanGoldfrad** [comment]
Hi @U1X6WK , here is my config.log file
[config.log](https://github.com/OpenVisualCloud/Immersive-Video-Sample/files/8631012/config.log)

**Comment by EitanGoldfrad** [comment]
#76 seems to solve it for me as well, thanks!

**Comment by U1X6WK** [comment]
> Hi @U1X6WK , here is my config.log file [config.log](https://github.com/OpenVisualCloud/Immersive-Video-Sample/files/8631012/config.log)

```
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -lthrift
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -lthriftnb
```

thrift was not installed correctly, please refer to #76 .
